### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by acalvino4** [jalendport/craft-hideadmin#12]
Any plans to support craft 4?

**Comment by wmdhosting** [comment]
waiting for this one too

**Comment by wmdhosting** [comment]
half year later :)

**Comment by jalendport** [comment]
Here's an update on where things are at: https://twitter.com/jalendport/status/1628813156888809475

**Comment by jalendport** [comment]
Just released [2.0.0-beta.1](https://github.com/jalendport/craft-hideadmin/releases/tag/2.0.0-beta.1), which is a fairly straightforward upgrade of the codebase to be Craft 4 ready. It's tagged as a beta at this point because I haven't had a chance to test it very thoroughly yet and I'd like to tweak a couple more things before I tag a final version of 2.0.0.

Thanks for y'all's patience - let me know if you run into issues with the new version and I'll make sure they're fixed right quick 💪
